"Constants that are critical to development"


HIGH_POLE_TAPE_HEIGHT_FROM_GROUND = 1.17 #meters
LOW_POLE_TAPE_HEIGHT_FROM_GROUND = .76 #meters
TAPE_HEIGHT = .005 #meters
LOW_POLE_DISTANCE_FROM_TOP = .20 #meters


HIGH_POLE_MIDPOINT_FROM_G = HIGH_POLE_TAPE_HEIGHT_FROM_GROUND - .5 * TAPE_HEIGHT
LOW_POLE_MIMDPOINT_FROM_G = LOW_POLE_TAPE_HEIGHT_FROM_GROUND - LOW_POLE_DISTANCE_FROM_TOP - .5 * TAPE_HEIGHT


HUE = [63, 130]
SAT = [21, 255]
VAL = [60, 255]


BLUR_RADIUS = 4


FILTER_CONTOUR_SOLIDITY = [91, 100]
MAX_CONTOUR_RATIO = .5 ##RATIO OF WIDTH TO HEIGHT OF BOUNDING BOX

PASSWORD = "gocrr639"